import { chromium } from "playwright";
const [, , email, companyId] = process.argv;
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const page = await browser.newPage();
page.on("console", (msg) => console.log("[console]", msg.type(), msg.text().slice(0, 200)));
await page.goto("http://127.0.0.1:3100/login");
await page.fill("#email", email);
await page.fill("#password", "E2ePasswort2026x");
await page.click("button[type=submit]");
await page.waitForURL("**/dashboard", { timeout: 20000 });
const response = await page.goto(`http://127.0.0.1:3100/companies/${companyId}`);
console.log("status", response?.status());
console.log((await page.content()).slice(0, 400));
await browser.close();
